spring.application.name=EcoScan_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/EcoScan_DB
spring.datasource.username=DSUser
spring.datasource.password=school123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8181

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect